// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRPOCdOx-secJw8OCXt9Fwm8JUjr9lAHg',
    appId: '1:826955651942:web:12e454630f413a3e2906a7',
    messagingSenderId: '826955651942',
    projectId: 'video-call-agora-81a71',
    authDomain: 'video-call-agora-81a71.firebaseapp.com',
    storageBucket: 'video-call-agora-81a71.firebasestorage.app',
    measurementId: 'G-RD2JEFVBED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbAT_Pyl-RWaUDporFiZCZjG4K0zELPtE',
    appId: '1:826955651942:android:ef3273cc9566f7022906a7',
    messagingSenderId: '826955651942',
    projectId: 'video-call-agora-81a71',
    storageBucket: 'video-call-agora-81a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxMb-MRwXNInysiemAyvNukYWVx9Fkuo',
    appId: '1:826955651942:ios:97df9d9bff53e2542906a7',
    messagingSenderId: '826955651942',
    projectId: 'video-call-agora-81a71',
    storageBucket: 'video-call-agora-81a71.firebasestorage.app',
    iosBundleId: 'com.example.videoCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxMb-MRwXNInysiemAyvNukYWVx9Fkuo',
    appId: '1:826955651942:ios:97df9d9bff53e2542906a7',
    messagingSenderId: '826955651942',
    projectId: 'video-call-agora-81a71',
    storageBucket: 'video-call-agora-81a71.firebasestorage.app',
    iosBundleId: 'com.example.videoCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRPOCdOx-secJw8OCXt9Fwm8JUjr9lAHg',
    appId: '1:826955651942:web:ea353aef682790392906a7',
    messagingSenderId: '826955651942',
    projectId: 'video-call-agora-81a71',
    authDomain: 'video-call-agora-81a71.firebaseapp.com',
    storageBucket: 'video-call-agora-81a71.firebasestorage.app',
    measurementId: 'G-32R1SJ7MZN',
  );
}
